spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test


uploadAddress:
  D:\zhuomian\homework\upload\
tempAddress:
  D:\zhuomian\homework\temp\
homeworkAddress:
  D:\zhuomian\homework\upload\homework\